sudo: false
language: node_js
node_js:
  - "node"
  - "7.6"
  - "7"
  - "8"
cache:
  directories:
    - node_modules
before_script:
  - npm install
script:
  - npm test
after_script:
  - npm run coverage
